dist: trusty
sudo: required
language: python
python:
  - 3.6
  - 3.5
  - 3.4
env:
  - CXX="g++-5" CC="gcc-5"
  - CXX="clang++-3.6" CC="clang-3.6"
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - $CXX
            - $CC
            - libboost1.55-all-dev
            - libnet-dev
            - libpcap-dev
            - linux-headers-`uname -r`

script:
  - python setup.py build
  - $CXX -Wall test.cpp dns.cpp -o test -lboost_unit_test_framework -std=c++11 -lpcap && ./test
  - cd firewall && make CC=`echo $CC`
  - $CXX -Wall test.cpp -o test -lboost_unit_test_framework -DCPP_TESTS && ./test
