dist: trusty
sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 3.4
env:
  - CXX="g++-5" CC="gcc-5"
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5
            - libboost1.55-all-dev
            - libnet-dev
            - libpcap-dev
#            - linux-headers-`uname -r`
# TODO clang

script:
  - python setup.py build
  - g++-5 -Wall test.cpp dns.cpp  -o test -lboost_unit_test_framework -std=c++11 -lpcap && ./test
#  - cd firewall && make
  - cd firewall && g++-5 -Wall test.cpp -o test -lboost_unit_test_framework -DCPP_TESTS && ./test
